---
- name: play2
  hosts: web_server
  vars:
     start_httpd: no
  tasks:
     - name: starting the httpd with var & con
       yum:
          name: httpd
          state: latest

     - name : stopping the httpd
       service: 
          name : httpd
          state: stopped
       when: start_httpd

     - debug:
         var: system_out.stdout_lines

     - name : starting the httpd
       service:
          name : httpd
          state: started
       when: start_httpd

     - command: systemctl status httpd
       register: system_out

     - debug:
         var: system_out.stdout_lines
